// プロジェクトデータの管理
export async function getProjects() {
    return [
        {
            slug: "seitaro-design",
            hero: "/images/SeitaroDesign/hero.jpg",
            title: "Seitaro Design",
            role: "front-end",
            date: "2024",
            url: "https://seitaro-design.com",
            description: "ブランディング、デザイン、ムービー、空間設計、アートといった、多岐に渡るクリエイティブ事業を展開しているセイタロウデザインのグループサイトが公開。IN FOCUSは、WEBサイト制作を担当しました。デザインにおける普遍的な要素の、形態、色、線、タイポグラフィによる遊び、余白や偶然性が入り込む仕掛けを入れています。それぞれの事業が独自の活動をしながらも、有機的に共存できる場所としての自由な実験空間を表現しました。",
            descriptionEn: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit",
            moviePc: "/movies/sd-pc.mp4",
            movieMotion01: `/images/SeitaroDesign/movie-motion-01.gif`,
            movieMotion02: "/images/SeitaroDesign/movie-motion-02.gif",
            imagePc01: "/images/SeitaroDesign/image-pc-01.jpg",
            imagePc02: "/images/SeitaroDesign/image-pc-02.jpg",
            imageSp01: "/images/SeitaroDesign/image-sp-01.jpg",
            imageSp02: "/images/SeitaroDesign/image-sp-02.jpg",
        },
        {
            slug: "seitaro-design-group",
            hero: "/images/SeitaroDesignGroup/hero.jpg",
            title: "Seitaro Design Group",
            role: "front-end",
            date: "2024",
            url: "https://seitaro.group/",
            description: "ブランディング、デザイン、ムービー、空間設計、アートといった、多岐に渡るクリエイティブ事業を展開しているセイタロウデザインのグループサイトが公開。<br/>デザインにおける普遍的な要素の、形態、色、線、タイポグラフィによる遊び、余白や偶然性が入り込む仕掛けを入れています。それぞれの事業が独自の活動をしながらも、有機的に共存できる場所としての自由な実験空間を表現しました。",
            descriptionEn: "Seitaro Design's group website is now open to the public. The company is engaged in a wide range of creative activities, including branding, design, movies, space design, and art.The site includes a play of universal elements in design, such as form, color, line, and typography, as well as a mechanism that allows for marginality and coincidence to enter.The site expresses a free experimental space as a place where each business can organically coexist while conducting their own activities.",
            moviePc: "/movies/sdg-pc.mp4",
            movieMotion01: `/images/SeitaroDesignGroup/movie-motion-01.gif`,
            movieMotion02: "/images/SeitaroDesignGroup/movie-motion-02.gif",
            imagePc01: "/images/SeitaroDesignGroup/image-pc-01.jpg",
            imagePc02: "/images/SeitaroDesignGroup/image-pc-02.jpg",
            imageSp01: "/images/SeitaroDesignGroup/image-sp-01.jpg",
            imageSp02: "/images/SeitaroDesignGroup/image-sp-02.jpg",
        },
        {
            slug: "canadagoose",
            hero: "/images/KaonaviTMP/hero.jpg",
            title: "CANADA GOOSE | FUMI NIKAIDO AND THE ART OF CRAFTSMANSHIP",
            role: "front-end",
            date: "2024",
            url: "",
            description: "社員の個性・才能を発掘し戦略人事を加速させるタレントマネジメントシステムを提供するカオナビが、タレントマネジメントのスキルを証明する資格制度 「Talent Management Professional」を創設。3D動画のイントロとWebGLを用いた奥行き感のある実装による没入型のwebサイトを通じて、宝石をモチーフにした認証資格のアイデンティティと、制度全体の世界観を表現しています。",
            descriptionEn: "Kaonavi, a company that provides a talent management system that accelerates strategic human resources by discovering and nurturing the individuality and talents of employees, has established a certification system for talent management skills called “Talent Management Professional”. Through a 3D video intro and a depth-of-field implementation using WebGL, the site expresses the identity of the certification system, which is based on the motif of a gem, and the overall worldview of the system.",
            moviePc: "/movies/cg-pc.mp4",
            movieMotion01: `/images/cg/movie-motion-01.gif`,
            movieMotion02: "/images/cg/movie-motion-02.gif",
            imagePc01: "/images/cg/image-pc-01.jpg",
            imagePc02: "/images/cg/image-pc-02.jpg",
            imageSp01: "/images/cg/image-sp-01.jpg",
            imageSp02: "/images/cg/image-sp-02.jpg",
        },
        // {
        //     slug: "kaonavi-tmp",
        //     hero: "/images/KaonaviTMP/hero.jpg",
        //     title: "Kaonavi - Talent Management Professional",
        //     role: "front-end",
        //     date: "2024",
        //     url: "https://lp-campus.kaonavi.jp/talent-management-pro/",
        //     description: "社員の個性・才能を発掘し戦略人事を加速させるタレントマネジメントシステムを提供するカオナビが、タレントマネジメントのスキルを証明する資格制度 「Talent Management Professional」を創設。3D動画のイントロとWebGLを用いた奥行き感のある実装による没入型のwebサイトを通じて、宝石をモチーフにした認証資格のアイデンティティと、制度全体の世界観を表現しています。",
        //     descriptionEn: "Kaonavi, a company that provides a talent management system that accelerates strategic human resources by discovering and nurturing the individuality and talents of employees, has established a certification system for talent management skills called “Talent Management Professional”. Through a 3D video intro and a depth-of-field implementation using WebGL, the site expresses the identity of the certification system, which is based on the motif of a gem, and the overall worldview of the system.",
        //     moviePc: "/images/KaonaviTMP/movie-pc.mp4",
        //     movieMotion01: `/images/KaonaviTMP/movie-motion-01.gif`,
        //     movieMotion02: "/images/KaonaviTMP/movie-motion-02.gif",
        //     imagePc01: "/images/KaonaviTMP/image-pc-01.jpg",
        //     imagePc02: "/images/KaonaviTMP/image-pc-02.jpg",
        //     imageSp01: "/images/KaonaviTMP/image-sp-01.jpg",
        //     imageSp02: "/images/KaonaviTMP/image-sp-02.jpg",
        // },
        {
            slug: "edifice",
            hero: "/images/Edifice/hero.jpg",
            title: "Edifice",
            role: "front-end",
            date: "2024",
            url: "https://baycrews.jp/feature/detail/12415",
            description: "フレンチシックをベースにしたモダンなスタイル提案で、大人のカジュアルをリードしてきたEDIFICEが今年で30周年を迎えました。30周年の積み重ねとともに構築されてきたブランドアイデンティを映像や音楽、本棚など様々なギミックとともにサイト全体に表現しています。",
            descriptionEn: "EDIFICE, a company that has led the modern style proposal based on French chic and has led the adult casual style, has celebrated its 30th anniversary this year. The site expresses the brand identity built over 30 years through a video, music, bookshelf, and various gimmicks.",
            moviePc: "/movies/edifice-pc.mp4",
            movieMotion01: `/images/Edifice/movie-motion-01.gif`,
            movieMotion02: "/images/Edifice/movie-motion-02.gif",
            imagePc01: "/images/Edifice/image-pc-01.jpg",
            imagePc02: "/images/Edifice/image-pc-02.jpg",
            imageSp01: "/images/Edifice/image-sp-01.jpg",
            imageSp02: "/images/Edifice/image-sp-02.jpg",
        },
        {
            slug: "workers-resort",
            hero: "/images/WorkersResort/hero.jpg",
            title: "Worker's Resort",
            role: "front-end",
            date: "2024",
            url: "https://www.workersresort.com/",
            description: "「働く」を、あたらしく。総務を、もっとクリエイティブに。オフィスをより良い環境へと進化させていくのに必要なヒントが集まる、オフィスマネージャーのためのリサーチネットワーク「Worker’s Resort」がリニューアル。メディアサイトのデザインリニューアルだけでなく、会員システムの導入、会員制のリサーチコミュニティ、記事のリクエストなど、総務（オフィスマネージャー）に向けたコンテンツも追加されました。ロゴは会員システムへの変更を受け、「より質の高い情報」を意識させるデザインにリニューアル。WebサイトはアプリUIを意識したパーツや、フォルダのあしらいなどを使い、コンテンツを整理しながらもサイトの特徴になるようなデザインにしています。パンフレットは以前制作を担当した「HOWHERE」の紹介も含めた、フロンティアコンサルティングが運営するWebメディアを紹介する内容となっています。",
            descriptionEn: `"Work" in a new way. Make general affairs more creative. Worker's Resort, a research network for office managers that gathers the tips needed to evolve offices into better environments, has been renewed. Not only was the media site redesigned, but a membership system was introduced, a members-only research community, article requests, and other content for general affairs (office managers) were added. The logo was redesigned to reflect the change to a membership system, and to make the site more "quality information" oriented, while the website was redesigned with application UI-conscious parts and folders to organize the content and make the site distinctive. The pamphlet introduces the web media operated by Frontier Consulting, including "HOWHERE," for which we were previously in charge of production.`,
            moviePc: "/movies/wr-pc.mp4",
            movieMotion01: `/images/WorkersResort/movie-motion-01.gif`,
            movieMotion02: "/images/WorkersResort/movie-motion-02.gif",
            imagePc01: "/images/WorkersResort/image-pc-01.jpg",
            imagePc02: "/images/WorkersResort/image-pc-02.jpg",
            imageSp01: "/images/WorkersResort/image-sp-01.jpg",
            imageSp02: "/images/WorkersResort/image-sp-02.jpg",
        },
        {
            slug: "journal-du-ete",
            hero: "/images/JournalDuEte/hero.jpg",
            title: "Journal du ete",
            role: "front-end",
            date: "2023",
            url: "https://journalduete.eteweb.com/",
            description: "“ジュエリーをもっと自由に楽しんでいただきたい”という想いのもと、シンプルな美しさを讃えながら、ひとさじの遊び心を添えたジュエリーを展開する「ete」のオウンドメディア「Journal du ete」。シーズン毎の特徴を企画性を持たせて記事化したり、普遍的なアイデンティティを紹介したりと、様々な切り口でブランドの多面的な魅力を伝えることを目指しています。",
            descriptionEn: "Journal du ete is an online magazine for ete, a brand that wants to make jewelry more fun and enjoyable. The site expresses the brand's multi-faceted charm through various angles, such as articles that feature the season's features with planning, and articles that introduce the brand's universal identity.",
            moviePc: "/movies/jde-pc.mp4",
            movieMotion01: `/images/JournalDuEte/movie-motion-01.gif`,
            movieMotion02: "/images/JournalDuEte/movie-motion-02.gif",
            imagePc01: "/images/JournalDuEte/image-pc-01.jpg",
            imagePc02: "/images/JournalDuEte/image-pc-02.jpg",
            imageSp01: "/images/JournalDuEte/image-sp-01.jpg",
            imageSp02: "/images/JournalDuEte/image-sp-02.jpg",
        },
        {
            slug: "taks",
            hero: "/images/Taks/hero.jpg",
            title: "TAKS",
            role: "front-end",
            date: "2022",
            url: "https://taks-task.jp/",
            description: "TAKSは、地域の宝である文化財の魅力や物語を発信する、文化コンテンツプラットフォーム。",
            descriptionEn: "TAKS is a cultural content platform that disseminates the charm and stories of cultural assets as regional treasures. The site expresses the charm and stories of cultural assets through a video, music, and various gimmicks.",
            moviePc: "/movies/taks-pc.mp4",
            movieMotion01: `/images/Taks/movie-motion-01.gif`,
            movieMotion02: "/images/Taks/movie-motion-02.gif",
            imagePc01: "/images/Taks/image-pc-01.jpg",
            imagePc02: "/images/Taks/image-pc-02.jpg",
            imageSp01: "/images/Taks/image-sp-01.jpg",
            imageSp02: "/images/Taks/image-sp-02.jpg",
        },
        {
            slug: "people-and-thought.",
            hero: "/images/PeopleAndThought/hero.jpg",
            title: "People and Thought.",
            role: "front-end",
            date: "2022",
            url: "https://p-a-t.jp/",
            description: "People and Thought.は、デザインを基軸に置きつつ、人の思考や現代において当たり前となってしまった感覚など、ベーシックとされてしまった思考に対して「疑問を見い出す」をテーマにした芸術活動です",
            descriptionEn: `People and Thought. is an art project that focuses on design while questioning the basic thoughts and perceptions that have become commonplace in modern society. The project explores the theme of "finding questions" in the basic thoughts and perceptions that have become commonplace in modern society.`,
            moviePc: "/movies/pat-pc.mp4",
            movieMotion01: `/images/PeopleAndThought/movie-motion-01.gif`,
            movieMotion02: "/images/PeopleAndThought/movie-motion-02.gif",
            imagePc01: "/images/PeopleAndThought/image-pc-01.jpg",
            imagePc02: "/images/PeopleAndThought/image-pc-02.jpg",
            imageSp01: "/images/PeopleAndThought/image-sp-01.jpg",
            imageSp02: "/images/PeopleAndThought/image-sp-02.jpg",
        },
    ]
}

export async function getProject(slug) {
    const projects = await getProjects()
    return projects.find((project) => project.slug === slug)
}
